refactor(devcontainer): remove sdk dep

diff --git a/.devcontainer/features/utils/bin/generate-docs b/.devcontainer/features/utils/bin/generate-docs
--- a/.devcontainer/features/utils/bin/generate-docs
+++ b/.devcontainer/features/utils/bin/generate-docs
@@ -2,33 +2,27 @@
 
 set -e
 
-eval "$(sdkmod logging)" || exit 1
-eval "$(sdkmod common)" || exit 1
-
-_FEATURE_NAME="utils.generate-docs"
-
 function main {
     local type
     type=$1
 
+    if [[ -z "$*" ]]; then
+        echo "Unepected argument(s): $*"
+    fi
+
     if ! [[ "$type" =~ ^(features|templates)$ ]]
     then
-        log error "Invalid type: $type. Must be 'features' or 'templates'."
+        echo "Invalid type: $type. Must be 'features' or 'templates'."
         return 1
     fi
 
-    log info "Generating $type documentation for devcontainers."
-
-    log info "Checking requirements."
-    if ! check_commands npx
+    if ! type npx > /dev/null 2>&1
     then
-        log error "npx is not installed. Please install npx and try again."
+        echo "npx is not installed. Please install npx and try again."
         return 1
-    else
-        log debug "Requirements check passed."
     fi
 
-    log info "Generating documentation."
+    echo "Generating $type documentation for devcontainers."
     if ! npx --yes "@devcontainers/cli" "$type" generate-docs \
         --registry ghcr.io \
         --namespace "froazin/devcontainer-$type" \
@@ -36,17 +30,12 @@ function main {
         --github-repo devcontainers \
         --project-folder "$type/src" > /dev/null 2>&1
     then
-        log error "Failed to generate documentation for devcontainers $type SDK."
+        echo "Failed to generate documentation for devcontainers $type SDK."
         return 1
-    else
-        log debug "$type documentation generated."
     fi
 
-    log info "Done."
+    echo "Done!"
     return 0
 }
 
-if ! main "$1"
-then
-    log fatal "Failed to generate documentation for devcontainers $1 SDK."
-fi
+main "$@" || exit 1
